tasks:
  - before: |
      curl https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor |
        sudo tee /etc/apt/trusted.gpg.d/google.gpg > /dev/null
      echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" |
        sudo tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
      sudo apt-get update
      sudo apt-get install --yes google-chrome-stable
    init: pipenv install --dev
    command: pipenv run python main.py

vscode:
  extensions:
    - ms-python.python
